
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthContextProvider } from "./context/authContext";
import Provider from "./Provider";
import LayoutProvider from "./components/LayoutProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "School connect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
          <LayoutProvider>
            <Navbar />
          {children}
          </LayoutProvider>
      
      </body>
    </html>
  );
}
